version: '3'
services: 
    node-api:
        build: 
            context: .
            dockerfile: dockerfile.dev
        ports: 
            - "3001:3001"
        volumes: 
            - /usr/src/shopfest/node_modules
            - ./:/usr/src/shopfest
        
